cmake_minimum_required(VERSION 3.20)
project(psio_consumer LANGUAGES CXX)
if(PSIO_SOURCE_DIR)
   include(FetchContent)
   FetchContent_Declare(psio SOURCE_DIR "${PSIO_SOURCE_DIR}")
   FetchContent_MakeAvailable(psio)
else()
   find_package(psio 0.1 CONFIG REQUIRED)
endif()
add_executable(psio_consumer main.cpp)
target_link_libraries(psio_consumer PRIVATE psio::psio)
enable_testing()
add_test(NAME psio_consumer COMMAND psio_consumer)
