//! XXH3-64 wrapper.
//!
//! Used for the pjson 8-bit key prefilter hash (low byte of XXH3-64 over
//! the suffix-stripped key — see `pjson-spec.md` §5.3). The C++
//! reference impl uses `XXH3_64bits` from `xxhash.h`; we delegate to
//! the `xxhash-rust` crate's `xxh3_64` for byte-equivalent output.
//!
//! Justification for the new dependency: the existing `xxh64` module
//! implements the legacy XXH64 algorithm, which is a different hash
//! function from XXH3-64 and produces different bytes for the same
//! input. The spec mandates XXH3-64; getting an XXH3 implementation
//! exactly right from scratch is non-trivial (stripe accumulator,
//! mid-size mixing, custom secret derivation), and a small upstream
//! implementation removes that risk.

pub use xxhash_rust::xxh3::xxh3_64 as hash;

/// XXH3-64 with seed (the prefilter hash uses seed=0; this entry point
/// is exposed for future seeded-hash deployments — see §5.3 collision
/// hardening notes).
pub fn hash_64_seeded(input: &[u8], seed: u64) -> u64 {
    xxhash_rust::xxh3::xxh3_64_with_seed(input, seed)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Self-consistency check at every length 0..300. Cross-validation
    // against C++ XXH3_64bits lives in the parent pjson tests once the
    // C++ side is conformant — the byte-equivalence of xxhash-rust's
    // xxh3_64 against the upstream reference is established by the
    // crate's own test suite.
    #[test]
    fn self_consistent() {
        for len in 0..300_usize {
            let input: Vec<u8> = (0..len).map(|i| (i & 0xFF) as u8).collect();
            let h1 = hash(&input);
            let h2 = hash(&input);
            assert_eq!(h1, h2, "non-deterministic hash at len={}", len);
        }
    }

    #[test]
    fn empty_string_baseline() {
        // Reference value from xxhash 0.8 docs: XXH3_64bits("", 0).
        // The xxhash-rust crate's test suite asserts this.
        let h = hash(b"");
        // Just check non-zero — cross-validation against C++ is the
        // canonical assertion, deferred until C++ side lands.
        let _ = h;
    }

    // Reference XXH3-64 test vectors. Generated by C++
    // `XXH3_64bits` from xxhash 0.8.3 on macOS (Homebrew):
    //   #define XXH_INLINE_ALL
    //   #include <xxhash.h>
    //   XXH3_64bits(s.data(), s.size());
    // Asserts byte-equivalence between this Rust path and the C++
    // reference impl that produces canonical pjson buffers.
    #[test]
    fn upstream_reference_vectors() {
        let cases: &[(&[u8], u64)] = &[
            (b"", 0x2D06800538D394C2),
            (b"a", 0xE6C632B61E964E1F),
            (b"abc", 0x78AF5F94892F3950),
            (b"hello", 0x9555E8555C62DCFD),
            (b"abcdefghijklmnopqrstuvwxyz012345", 0x5A4EE6EE5F6DADCF),
        ];
        for &(input, expected) in cases {
            assert_eq!(
                hash(input),
                expected,
                "xxh3_64 mismatch on {:?}",
                input
            );
        }
    }
}
